eslint 작업

diff --git a/.github/workflows/assignment-6-ci.yml b/.github/workflows/assignment-6-ci.yml
--- a/.github/workflows/assignment-6-ci.yml
+++ b/.github/workflows/assignment-6-ci.yml
@@ -30,12 +30,12 @@ jobs:
       - name: job1 구현
         run: |
           set -e
-          if ! pnpm run build; then
+          if ! pnpm -F assignment-6 build; then
             echo "TypeScript build failed" > tsc_error.txt
           fi
         working-directory: packages/assignment-6
 
-      - name: Check for build errors
+      - name: 빌드 에러 체크
         id: check_build_error
         run: |
           if [ -f packages/assignment-6/tsc_error.txt ]; then
@@ -44,7 +44,7 @@ jobs:
             echo "::set-output name=build_error::false"
           fi
 
-      - name: Comment on PR if build fails
+      - name: 빌드 오류 코멘트
         if: steps.check_build_error.outputs.build_error == 'true'
         uses: actions/github-script@v4
         with:
@@ -65,6 +65,33 @@ jobs:
       - name: job2 구현
         run: echo "job2의 내용을 구현해주세요"
 
+    - name: Run ESLint
+        run: pnpm exec eslint . --format json --output-file eslint-report.json
+        continue-on-error: true
+
+      - name: Check if ESLint report contains errors
+        id: eslint-check
+        run: |
+          if grep -q '"errorCount": 0' eslint-report.json; then
+            echo "eslint-errors=false" >> $GITHUB_ENV
+          else
+            echo "eslint-errors=true" >> $GITHUB_ENV
+          fi
+
+      - name: Add a comment to the PR if there are ESLint errors
+        if: env.eslint-errors == 'true'
+        uses: marocchino/sticky-pull-request-comment@v2
+        with:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          header: ESLint Report
+          path: eslint-report.json
+
+      - name: Upload ESLint report
+        if: env.eslint-errors == 'true'
+        uses: actions/upload-artifact@v3
+        with:
+          name: eslint-report
+          path: eslint-report.json
   test:
     runs-on: ubuntu-latest
     steps:
