패키지 설치과정 추가

diff --git a/.github/workflows/assignment-6-ci.yml b/.github/workflows/assignment-6-ci.yml
--- a/.github/workflows/assignment-6-ci.yml
+++ b/.github/workflows/assignment-6-ci.yml
@@ -20,6 +20,16 @@ jobs:
       - name: List assignment-6 files
         run: ls -R packages/assignment-6
 
+      - name: 패키지 설치
+        run: npm install
+        working-directory: packages/assignment-6
+
+      - name: tsc 실행
+        id: run_tsc
+        run: |
+          npm run tsc || echo "TypeScript build failed" > packages/assignment-6/tsc_error.txt
+        working-directory: packages/assignment-6
+
       - name: job1 구현
         run: npm run build || echo "TypeScript build failed" > packages/assignment-6/tsc_error.txt
         working-directory: packages/assignment-6
